prometheus-operator-crds:
  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true 
kube-prometheus-stack:
  crds:
    enabled: false
  prometheusOperator:
    revisionHistoryLimit: 0
  prometheus:
    prometheusSpec:
      probeSelectorNilUsesHelmValues: false
      scrapeConfigSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
  grafana:
    assertNoLeakedSecrets: false
    revisionHistoryLimit: 0
    replicas: 1
    initChownData: false
    defaultDashboardsTimezone: Europe/Amsterdam
    ingress:
      enabled: true
      hosts: 
      - grafana.mobrockers.com
      tls:
        - hosts:
          - grafana.mobrockers.com
    sidecar:
      alerts:
        enabled: false
        searchNamespace: ALL
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: false
        searchNamespace: ALL
      plugins:
        enabled: false
        searchNamespace: ALL
      notifiers:
        enabled: false
        searchNamespace: ALL
  kube-state-metrics:
    revisionHistoryLimit: 0
  prometheus-node-exporter:
    revisionHistoryLimit: 0
