apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: radarr
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: radarr
        app.kubernetes.io/name: radarr 
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 5000
      containers:
        - name: radarr
          image: '{{ .Values.radarr.image.repository }}:{{ .Values.radarr.image.tag }}'
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: '1000'
            - name: PGID
              value: '5000'
          ports:
            - name: http
              protocol: TCP
              containerPort: 7878
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /media
        - name: exportarr
          image: '{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}'
          args:
            - radarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://localhost:7878"
            - name: CONFIG
              value: /config/config.xml
          ports:
            - name: metrics
              containerPort: 9707
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
        - name: additional-exportarr
          image: '{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}'
          args:
            - radarr
          env:
            - name: PORT
              value: "9708"
            - name: URL
              value: "http://localhost:7878"
            - name: CONFIG
              value: /config/config.xml
            - name: ENABLE_ADDITIONAL_METRICS
              value: "true"
          ports:
            - name: more-metrics
              containerPort: 9708
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: radarr-data
        - name: media
          persistentVolumeClaim:
            claimName: radarr-media
  