apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: radarr
      app.kubernetes.io/name: radarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: radarr
        app.kubernetes.io/name: radarr 
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 5000
      containers:
        - name: radarr
          image: '{{ .Values.radarr.image.repository }}:{{ .Values.radarr.image.tag }}'
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: '1000'
            - name: PGID
              value: '5000'
          ports:
            - name: http
              protocol: TCP
              containerPort: 7878
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: radarr-data
        - name: media
          persistentVolumeClaim:
            claimName: radarr-media
  