apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr
      app.kubernetes.io/instance: radarr
  endpoints:
    - port: metrics
      interval: 15m
      scrapeTimeout: 90s
      path: /metrics
    - port: more-metrics
      interval: 12h
      scrapeTimeout: 1h
      path: /metrics
