cilium:
  k8sServiceHost: k8s.mobrockers.com
  k8sServicePort: 6443
  kubeProxyReplacement: strict
  rollOutCiliumPods: true
  tolerations:
    - operator: Exists
    - operator: Equal
  operator:
    rollOutPods: true
    tolerations:
    - operator: Exists
    - operator: Equal

  ipam:
    mode: kubernetes

  bgpControlPlane:
    enabled: true

  hostFirewall:
    enabled: true
  
  gatewayAPI:
    enabled: true

  hubble:
    enabled: true
    tls:
      auto:
        method: cronJob
    relay:
      enabled: true
      rollOutPods: true
      tolerations:
      - operator: Equal
    ui:
      enabled: true
      rollOutPods: true
      tolerations:
      - operator: Equal
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://hubble.mobrockers.com/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - hubble.mobrockers.com
        tls:
          - hosts:
              - hubble.mobrockers.com

  securityContext:
    capabilities:
      ciliumAgent: [CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID]
      cleanCiliumState: [NET_ADMIN,SYS_ADMIN,SYS_RESOURCE]
  cgroup:
    autoMount:
      enabled: false                        
    hostRoot: /sys/fs/cgroup     

  certgen:
    ttlSecondsAfterFinished: null
    tolerations:
    - operator: Equal
  prometheus:
    serviceMonitor:
      enabled: true
