apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "adguard.fullname" . }}-primary
  labels:
    app.kubernetes.io/name: {{ template "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
    {{- include "labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "adguard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "adguard-primary"
      {{- include "labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "adguard.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "adguard-primary"
        {{- include "labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: adguard-sync
          image: "{{ .Values.sync.image.registry }}/{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag }}"
          restartPolicy: Always
          imagePullPolicy: IfNotPresent
          args:
            - run
          envFrom:
            - configMapRef:
                name: {{ template "adguard.fullname" . }}-sync-config
          ports:
            - name: sync
              protocol: TCP
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: sync
              path: /metrics
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              port: sync
              path: /metrics
            failureThreshold: 5
            periodSeconds: 10
      containers:
        - name: adguard
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "Europe/Amsterdam"
          args:
            - --web-addr
            - 0.0.0.0:3000
            - --no-check-update
          ports:
            - name: web
              protocol: TCP
              containerPort: 3000
          resources: {{ toYaml .Values.primary.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/conf
              subPath: conf
            - name: data
              mountPath: /opt/adguardhome/work
              subPath: work
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "adguard.fullname" . }}-primary-data
      tolerations:
      - key: essential
        operator: Exists
