{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "adguard.fullname" . }}
  annotations: {{ toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
    {{- include "labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - backend:
              service:
                name:  {{ template "adguard.fullname" . }}-primary
                port:
                  name: web
            path: /
            pathType: Prefix
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
  {{- end }}
{{ end }}
