apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "adguard.fullname" . }}-primary-data
  labels:
    app.kubernetes.io/name: {{ template "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
    {{- include "labels" . | nindent 4 }}
    {{- with .Values.persistence.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
