apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "adguard.fullname" . }}-primary
  labels:
    app.kubernetes.io/name: {{ template "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
    {{- include "labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "adguard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "adguard-primary"
  endpoints:
    - port: sync
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
