apiVersion: v1
kind: Service
metadata:
  name: {{ template "adguard.fullname" . }}-primary
  labels:
    app.kubernetes.io/name: {{ template "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard"
    {{- include "labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 3000
      targetPort: web
      protocol: TCP
    - name: sync
      port: 8080
      targetPort: sync
  selector:
    app.kubernetes.io/name: {{ template "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-primary"
