apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "homeAssistant.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "homeAssistant.fullname" . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "homeAssistant.fullname" . }}-role-binding
roleRef:
  kind: Role
  name: {{ template "homeAssistant.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ template "homeAssistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
