apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "homeAssistant.fullname" . }}-automations
  labels:
    home-assistant-config: "1"
  annotations:
    io.home-assistant/config-folder: "/config/automations"
data:
{{ (.Files.Glob "configuration/automations/**.yaml").AsConfig | indent 2 }}
