apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  annotations:
      nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  rules:
    - host: plex.mobrockers.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: plex
                port:
                  name: http
            pathType: Prefix
  tls:
    - hosts:
        - plex.mobrockers.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli-auth
  namespace: authentik
spec:
  rules:
    - host: tautulli.mobrockers.com
      http:
        paths: 
          - path: /outpost.goauthentik.io
            pathType: Prefix
            backend:
              service:
                name: ak-outpost-authentik-embedded-outpost
                port:
                  number: 9000
  tls:
    - hosts:
        - tautulli.mobrockers.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  annotations:
    nginx.ingress.kubernetes.io/auth-url: |-
        http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: |-
        https://tautulli.mobrockers.com/outpost.goauthentik.io/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: |-
        Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
        proxy_set_header X-Forwarded-Host $http_host;
spec:
  rules:
    - host: tautulli.mobrockers.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: plex
                port:
                  name: tautulli-http
            pathType: Prefix
  tls:
    - hosts:
        - tautulli.mobrockers.com