apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
spec:
  serviceName: plex
  selector:
    matchLabels:
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: plex
    spec:
      containers:
      - name: plex
        image: '{{ .Values.plex.image.repository }}:{{ .Values.plex.image.tag }}'
        ports:
        - name: http
          containerPort: 32400
        env:
          - name: TZ
            value: TZ=Europe/Amsterdam
          - name: PUID
            value: '1000'
          - name: PGID
            value: '5000'
          - name: VERSION
            value: docker
        resources: 
          limits: 
            gpu.intel.com/i915: "1" 
        volumeMounts:
        - name: pms-transcode
          mountPath: /transcode
        - name: pms-config
          mountPath: /config
        - name: media
          mountPath: /media
      volumes:
      - name: pms-transcode
        emptyDir: {}
      - name: media
        persistentVolumeClaim:
          claimName: plex-media
  volumeClaimTemplates:
  - metadata:
      name: pms-config
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
