gatus:
  ingress:
    enabled: true
    hosts:
    - status.mobrockers.com
    tls:
    - hosts:
      - status.mobrockers.com
  
  config:
    endpoints:
    - name: argocd
      url: https://argocd.mobrockers.com
      group: inhouse
      conditions:
      - '[STATUS] == 200'
    - name: argocd
      url: https://argocd.mobrockers.com
      group: external
      conditions:
      - '[STATUS] == 200'
      client:
        dns-resolver: 'udp://1.1.1.1:53'
    - name: tls-ldaps
      url: 'tls://ldap.mobrockers.com:636'
      group: inhouse
      conditions:
        - '[CONNECTED] == true'
        - '[CERTIFICATE_EXPIRATION] > 48h'
      client:
        insecure: true
