global:
  revisionHistoryLimit: 0

  volumes:
  - name: postgres-credentials
    secret:
      secretName: authentik-data-app
  volumeMounts:
    - name: postgres-credentials
      mountPath: /postgres-credentials
      readOnly: true
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret
          key: secretKey
    - name: AUTHENTIK_POSTGRESQL__USE_PGBOUNCER
      value: "true"
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__HOST
      value: env://AUTHENTIK_DATA_R_SERVICE_HOST
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__NAME
      value: file:///postgres-credentials/dbname
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__USER
      value: file:///postgres-credentials/username
    - name: AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PASSWORD
      value: file:///postgres-credentials/password

authentik:
  authentik:
    postgresql:
      host: env://AUTHENTIK_DATA_RW_SERVICE_HOST
      name: file:///postgres-credentials/dbname
      user: file:///postgres-credentials/username
      password: file:///postgres-credentials/password

  server:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    ingress:
      enabled: true
      hosts:
        - authentik.mobrockers.com
      tls:
        - hosts:
          - authentik.mobrockers.com

  redis:
    enabled: true

  prometheus:
    rules: 
      enabled: true
