apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-nfs-ssd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    targetRevision: HEAD
    path: apps/democratic-csi/chart
    helm:
      valueFiles:
      - ../nfs-ssd-values.yaml
  syncPolicy: {}
  destination:
    name: in-cluster
    namespace: democratic-csi-nfs-ssd
