apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/argo-cd
    targetRevision: HEAD
  syncPolicy: {}
  destination:
    name: in-cluster
    namespace: argo-cd
