apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/cert-manager
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: cert-manager
