apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-gateway
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/cilium-gateway
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: cilium-gateway
