apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/_base
    targetRevision: HEAD
    helm:
      valueFiles:
      - core-apps.yaml
      - csi-apps.yaml
      - connectivity-apps.yaml
      - home-automation.yaml
      - mediacenter.yaml
      - apps.yaml
  syncPolicy:
    syncOptions:
     - FailOnSharedResource=true
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: argocd
