apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/_base
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: argo-cd
