apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/_base
    targetRevision: HEAD
    helm:
      valueFiles:
      - core-apps.yaml
      - csi-apps.yaml
      - connectivity-apps.yaml
      - arr-apps.yaml
      - apps.yaml
  syncPolicy: {}
    # automated:
    #   prune: true
    #   selfHeal: true
  destination:
    name: in-cluster
    namespace: argocd
