apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/ingress-nginx
    targetRevision: HEAD
  syncPolicy: {}
  destination:
    name: in-cluster
    namespace: ingress-nginx
