apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/intel-device-operator
    targetRevision: HEAD
  ignoreDifferences:
  - group: deviceplugin.intel.com
    kind: GpuDevicePlugin
    jsonPointers:
    - /spec/resourceManager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: intel-device-operator
