ingress-nginx:
  revisionHistoryLimit: 0

  controller:

    allowSnippetAnnotations: true
    ingressClassResource:
      default: true

    service:
      enabled: true
      external:
        enabled: false 
      internal:
        enabled: true
        annotations: 
          'io.cilium/lb-ipam-ips': 10.0.10.130
        externalTrafficPolicy: Local

    extraArgs:
      default-ssl-certificate: ingress-nginx/default-wildcard-certificate
      update-status-on-shutdown: 'false'
