apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: prowlarr
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prowlarr
        app.kubernetes.io/name: prowlarr 
    spec:
      automountServiceAccountToken: false
      initContainers:
        - name: configure-prowlarr
          image: '{{ .Values.images.alpine.repository }}:{{ .Values.images.alpine.version }}'
          command:
            - "sh"
            - "/init-prowlarr/init-prowlarr.sh"
          volumeMounts:
            - mountPath: /init-prowlarr
              name: init-files-prowlarr
            - mountPath: /config
              name: data
              readOnly: false
      containers:
        - name: prowlarr
          image: '{{ .Values.images.prowlarr.repository }}:{{ .Values.images.prowlarr.version }}'
          env:
            - name: TZ
              value: TZ=Europe/Amsterdam
            - name: S6_READ_ONLY_ROOT # Apparently this thing is needed when running with read only root filesystem
              value: 1
          ports:
            - containerPort: 9696
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: data
              readOnly: false
            # - name: devshm
            #   mountPath: /dev/shm
            #   readOnly: false
            # - name: shared
            #   mountPath: /shared
            #   readOnly: false
            # - name: tmp
            #   mountPath: /tmp
            #   readOnly: false
            # - name: varlogs
            #   mountPath: /var/logs
            #   readOnly: false
            - name: varrun
              mountPath: /var/run
              readOnly: false

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: init-files-prowlarr
          configMap:
            name: init-prowlarr-cm
        - name: data
          persistentVolumeClaim:
            claimName: prowlarr-data
        # - name: devshm
        #   emptyDir:
        #     medium: Memory
        # - name: shared
        #   emptyDir: {}
        # - name: tmp
        #   emptyDir: {}
        # - name: varlogs
        #   emptyDir: {}
        - name: varrun
          emptyDir:
            medium: Memory