democratic-csi:
  # talos config
  node:
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /usr/local/etc/iscsi
      iscsiDirHostPathType: ""

  csiDriver:
    name: "org.democratic-csi.iscsi.slow"

  storageClasses:
  - name: truenas-iscsi-slow
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4

    mountOptions:
    - noatime
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-iscsi-slow-config
    config:
      driver: freenas-api-iscsi # required

driverConfigFileSealed: 
  value: 'AgAvk4+7z/ewEJ0xtbCzKrkGC46Ya3Expafh0nulsTaLEwi91xL83FZj2l6iYPCQTHKFa5dWkrs0oFbvJSIiD420gN21z5WiT/A8wKSzr2MC/zyMYYB2Mn+k2Vl8JVhHQkqofEL/LSes6x55vRipuZmJTm37BDsjmJWEx5eHxguRXNv0dEjNOKEDMRMZKlG3qa/dDACF/3ujh8Xy8/6EEwIhc04r89NlRBJO2xM0ONsmEipm0vDhQRmq8VR0Bg2+/Ow/lmdnntkoqGiHz9ahwD8XkC6+UZmlCgeveFhsu7meHt1J5P2N7TdME5dAVz2c1Ac54lXqsR3d66wphl/8WW2iZqAdvrkZqk/XP+QMmnsNgJBouOCXlPsLgEoB3qd2tN7CrIAhs7XsoLMTN4/WFo/aHNaALesG+/cDCFj4R/a2MPjc6Gwb7UOufyeFh70w84lmCZ7jdSLoBIEPt269YQqxBM/6HuhaYN7f0ngeufYHhQrUSxvcb0N14nP8MBEN3Ez7rFwptuc8eL6VP1evyUk6RaIiW0HhtDaa/vqzjQhALmp8dQVAM//DDi8P76SDsbf2+ukJ6/R5L03DVibVR8Oc9m5x3pyK7jaCX6/ErHVD+OurvQH0o1FXU+gSYvkTKJGIrOH4UxxnbtC/KOmndx4W8R9MkbyqgmI+9wTKLlR5Qs52rD8dJmQBARo/wFng7muc1xUI+EawqOaluRChbAARXBp0LcyaSNUESbqlfPsfNKAHeD6Wbz1H4riWminYHDMvH4TePpp24gMSwhQqHjZPoW9enLiGSsD7EkCD/yZ14jOtmLQ7zi1oTwbD7qXRkKuPXOt0bTjIT+Y7IJ8H4OfQP56YjrlsktaVxXO30RtPjTOYxTsGVHRtNfyWjsNdhP8nuWOxgxqxyl0EBmrZxRoRcOvG/klyAh5+yEpuxsaxSNs7XTgyT1cHkHiZ9fWxoTSODEINfoWjmr8kXZB7LYUUD6+nWMTLJesyYsPBW4wgDpw3owcoQR+oLwpwvjMkB0dg5u+j6MiTp3d9+J7i04I15LCUJbaLfwlxA+PceomJob49udyETp1V/nOEF7Wdw+In4huufg+Q0LhPsoF/XXvTCe8rNunGqZfLpXfaI/2emSwbkUEQH6CYBeofFwjbr2/GaU/Frg8J9mldcA4b0ye5kq+V4RR3c2Nd90tSiTIseaQWirx+pQNghh94EQ2L1jpvs3jehqoIDGsnSsUaxBGhIC4VzuzpzzTntQ1ppSHDq6RmgWQZnKBLZUVuL1x/8oOh2cfjgS3YPydk1GKSgFAMuEiqDXsArG329xIg9CHVo/UixzIrotGTavYu2wMpjly5WF9MBE6z3Q824QAJfFCu27prfqJQi5hIZSOBuqMs0sIXu59S0CqI7hjTaUKfVGU9JfrY+xG1biZVXMpmzoyO8wwmUHaRd2bdXOixi1qUioMFR8viU+CHmLziidDWE+W4gH7ObWG3hUVKa6gAkFuSQHEZC8SPh8avLXmVRPWdMi/SmgXawU/gI9+dDt8dEfDMvZBwnF8Mi6XQTcJ3Ndms3cQWgoLmJZBE2YbaOnqRpTl/RJYlgvpD65H1smIipHGwyp3vXCJNuiR5Fiw3e6I7Uku603oz1w5W+jOC7S38T5gTAltEpNXYpO+Q52AtqLWWwcmF/89j+UdmylzEQ7S+shiLoIHm8QrtrCaT+L6arPuU6mxzqjvq35t4IGOYc+rcFu8f/Gy1ihh3lO8cA/tcuOImfoNPpgoBGfZxv/pKbfX2AOODqz5cSyVwJcz8yksVoYbBIDOitDCwXUmQNPJ+FMs7upBtK9bYaXtSx3em4Q0jMH40w2wB9ogcQBXmwDQit//iYnBgUB/PcQmVuWWPI/mnkgzIWlyMqQhyRk4fqAJhCFXW6T+QNVf3p7M9HSDHqIo6QmMTw23fsmaiGAb+ay+WZVU4nAAr2UwtLAZhvfAkXHdxXnR2YAhwwGmDUCHIb19dQkP9DNYQDG4mGDjHCAf78DRDlLRI0o6uYV13pv1I/R+aBM+TdDGmp23NSE75NuhM9NZby0IIh4sP55yBjqPryAdRcplQhqcvaWEDrng8rnn4kRuk+SB9+ox3K05dDrgPvXSeLoI1F1WiBhLlINEAA1JsIlZFSp7VE73U6wn6Kj8GxBU3Mut/fSHw4eYVfk5gPx4mu8C5wvyRJsGRSAu/epOUPkzl+CYAwIkzJU/NyG+cYI1JQ9U+FCdClHtAUN4mlQshtZqkS2Xi/oeNnWGLM2unBcAUZ2/FkDmrnAJXxpmywjgf5i9K79cSTZKd63qDf1k/ha+YP/xbFYOAItQeiLIVJl4vyyP6G9k8qvBRuxqKfoOayGnhoMNnsGPCfLJlx0AmLzpvhYyXqf7PtK1kco+/nlF6p2ffvbDugbs+uEW3hEmgoqAHo8G0/XHRZKwOGO384yZPo7VTe/fLN+8oXarzsodehu4iClY4r7NAORJHTEd/2YvzZJYdizkJkR0MWJuzNumbbZLertW7Jj5eXgFBJ6whcHzwGI9+dInqq3lzhMJQEvUTNyzXrRNYcJkvOMRuKpGZ7RquhMhJcGdCthkh7lRMzUnRl556yvha44E3q6ncbWwj82IvCzVrnnBebtVsXzaZ4A6eez2ulW6XznWM3I4LVKKXpDPUYkr76rLYSlb8y7aXbWYxUx7ascug0+Sr37ahDT2yHqLoZEBdwMzil8PKPhckFLhwSJxNiyjGsIFpAbnEQMS3ZCTE/4wcgIvi0p8yR8t/oPnK/94NNLW7qaezptWW8vhtGdJMdnINgAr5n52YV3ZjppC2KYM2UvFVryO0d+HTPdhLgsMVl8bFx4WOQMaVgnD+KLNrpCUb8ATGxJVC+Ls041Ezcj8UvfNtWbroINI6ZIQjUuy/Zb6OT9T3naecptrujSs0HT9dDh6lLUHhD8NF9BZEkSRm7cUlbYAXPDidTEKT/PHavk7OVxKui5X+8Sigj6z71b8KDkb/27EBb74ivHFEcOgND4WVZAiBZT4H+cm73OH7vB7CnEk9rNMEOV1CniCSngWUrhlbGftH7Xdvj17UW2J3jwdVqLs3aeTkLHOf3LrCuGw7qKVzRZ1boZIOFaeyvMqOWLl4/o8a9Jfu3/NhDSsMUIR15tzQ4ljNybGsCThr4W8czmimwo35P7Ke5T3N8F42uk2n7xehTr/1HwgeRplGRw0svcmN8BU/RSwYLAoM3IOonbQjyNAnM4p9zI/sbzwxprJBPX/OkWZ8y/xyGS0Zue7V0GiwZxltKH3nalvt9GLDMZcvm9tqpbowsAo+lw=='