democratic-csi:
  # talos config
  node:
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /usr/local/etc/iscsi
      iscsiDirHostPathType: ""

  csiDriver:
    name: "org.democratic-csi.iscsi.hdd"

  storageClasses:
  - name: truenas-iscsi-hdd
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype" = "ext4"

    # secrets:
    #   node-stage-secret:
    #     node-db.node.session.auth.authmethod: CHAP
    #     node-db.node.session.auth.username: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME}
    #     node-db.node.session.auth.password: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD}
    #     node-db.node.session.auth.username_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME_IN}
    #     node-db.node.session.auth.password_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD_IN}

  driver:
    existingConfigSecret: truenas-iscsi-hdd-config
    config:
      driver: freenas-api-iscsi # required

driverConfigFileSealed: 
  value: AgBlEhooDOPUd8KAL3NiK/cZQ7rq0lvmNT96q/z0uqjrDdUX31SRzmFz6B35mmw4qhz23fJoUdE1x54QVh5xk/d3R3dP27NiRsvhR5rATG37prL/6YE/Q2hTFogsELfqUUn4FCwTmu8O4dBRGiHsHL4vFjr+NM4x7i4dn2eQRDOc3Y4/r/SF3Zq+Pw85NWDFllzshxgMWtotjCmmN7dqSmFujVwkkSVCRPP6gPofCnkj3Ehn6JiJmdVMHTMSoeJDEerJuwB+2c9J32JDaBXon8Wt9JlwAKpYRuTh46d092WBvTBfbv1pFTfYrkwfZqiUKgNP5vVM9+yR6khE1K3janL1T78+a5/WjdXci1XUQpnamJ2mw2p/oNJ1xbMsGNB7651x0bQknCfiBaOsxpS+fISbYDPZ3hZnvkf8SuFxB6gu0fQHBNokksL1cnj0m0m1mjT+pcRVA3TJloO7vh6mxEAGvap3BNFjYR8zlGtMPMbqfnzoUlwinouYk4wsDxKy2OG5fiPggeg+3nfUXfIgJ0TUZN0H37IqzFETbobIagSD3cEWoER3XRzj1IHniRNP9HKde9YUhGmJTVh9dPOk0tYfOfQiexGeYwoCI8B3U5897RgYMNbxkF38NHEjB2Ub87Iu3dGM/fpaxahyGg0z6z9g5qyK6J+Ux9aZ8TKi58CX95wIsPPxcqJo+dwwnIbhB3Slf2DDMKDERGkzLdX1BdkhuyUYBUBOrXSOZqVzzWRkrvzEBFE3E4VlO9gZBszyLo/dRCdDi7Dn2j/3qRLOcFSjAdB3WH0Y/iGQFPSJZsYmsEjHt8jPBsgU8nMUSKX+QZLlGeeXKuOcvcKZMImk+EsrDAYMjkWvP0KEaB5oN62gkbcLqy7qnVIbKxkeqO7Y8FZ9mAXFI3daFrBynyzUqqQ3wEL9WTzvL5cESxLU6H1TTZepFi2qqioq+AHnDeqFq76OkmlICr2cOdA9HkLRv2VHo81CaNzcu7vaNvHmZl1Y6tXqltH8ChXheQtktfHWbFFp5VTWzMaamh1pbMhApXmNbhFa+sbVJdvvHpDIQdJxgI7ANRHFE/OyDoHpqO7Dt/KSnsL6nJRejTXHoad+NYeAfhpdj84wtRUybM6m/IK4hCsDcYoLmIxOIfhH2RNPmn53GtCzL4gyUpkeQ5kMj97Sb8PL+k/Ox4i6IcVkub0j+BhhJokrmtGwK8aRg95ZcdWk3HBM1jCxsEAPY7EtL8uDKCqE8ls7wOdredb/JB/sur6O29JcKVDy6h9rndpZ5UK0dlq8OkgYO9zJhMz6Nh9LbBlP7ZjF2ba7/NdZTzyHg0ktvZhaUHlysMOWFIhiRbrF0FpdilakAKde06n0YnUszCTYCwen/kZGhEkCzJW72k3j/QdGx0ipp9d8o9mROLdnQKctm7bQb9ixkRKUl12x2Cpx1+M2QMosiDJO/6z+e1FJe1v/RXnJjgi7kBozzPdhmEFGa/QcVCj0bL+ME0H9G+U17MOU86Ua2YCENv4d0TQkeD18uht0ExK0P7nlIMV7XaO7DntxRtGgBBDcra95tUF+/Y83LS4MWE8G1BxUK6kzLxvLbmTEzeYyI9Ykg8g0ggNAoayydRM6sE5kfMlmDV+rI1Z14UxoNpVba5zVhBj0C1JpyReKsxHK9Nyrvv1Jf0UFtGqNl8c/BTJKXwJSS/HzTIE4XchhY8u/BHMhCfdYPY6n2CvD0GxJ3ZDv+NNndi9uRGfZjyrcJ/QpOIYyWxAqXMvNyJ0BB/3V874Ud3kqxvaPjBcJROz1fhAuheg+c6cS50yMGPriSiihMbbkOeA70v2dPapBxZnM4j2RRawmPyNwkMajtRHbXiARKklqBBQuqKgFFdE47ObnXL1JjFoO4NrW44CwwtaEX4cUIvOhqzOTLUlFFb06Ay9fSEtfsr7m8cf3uti/fdlzoxn+laBz1cnCuN/SwAsqhMEBNVSCqeoonZ23kUazZDUpRNhNvWehBWjU6MWd5hmFblaGVXhij2LaOYKXLS/cl7Tks58cmTVjIsURx2SSXw+KTfBQ5nhpmYauK4gK15yF5HpSo1xaSpfzbBetXEHbMMXz2Z9FgqZVs4CLLAfsjwepNdfK2rjkUoyR5aH+ojxRuLuVY/o922CDCqShOyU6AVq64QUGa1hP5z4vKCHx7ObVB4g6ymmitLb8lBUQg4ZKN5788dNac6H9kv/IMJb/JQbKOr1UI+6x7OYlQHEUDDEvzDuJ7Qv5BUtr5dX6fCD6HDfHBtWMaKFw2XnkTz1t4iGt/Ri1ewuWVY5TJPf4jUnDwfKdm/IHEJFi08l1r+4iwHnZ8s39HkfMz17Y+MiGL/+v1Bso9PYhEjJ+6CEx7FS03uE0r5wzv4c1tYmzl8Tbj4ZR1ZzaFbM1pP48vn8CFK225bJR44ZEviYzRRl4Ewl5SU+ebu0qKI2/TPy8TY/LsC5vIvuOjjzKXXF9whTObC/56kyW3+qlMgxAg3wagWrADXoxLwoETchrwQqHAxN0ZQ5RqxiNt/tqYXAbRcIvJAklEBkhASCQA3uf6ir1zWVjRsvJil2Kb2/1HtX7B+3G0uEJYm8SCyFvN9yA1p4z8LAXlhh86LtIc8+EsinWy2dQg1qy952ieeq3ua7rBdXwLIJIgqMpjBdd9K1aFRkSEU3rIukviAf+v1heD97k3wPQ702HLt2I3q5UDqKUocN/Ibc59j2jmootv6FKOhiwwPXpAChSpBgI40UdL1awdF5MTthQOTMLrCCn8C2AXnDQw5nm9hGZMuh6/av0jNPUvXOS47w2bnmuvi8JijDe5KX4O91Zg/DyAVeufiTxYSqlduKWyZ8dLFxU1+GDFtFMuOwKfqpRaDkz7iPnV16EkGK8KE51GVU6miVkxd5l5MU=