democratic-csi:

  node:
    # talos config
    hostPID: true
    driver:
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /usr/local/etc/iscsi
      iscsiDirHostPathType: ""
    # talos config
      # logLevel: debug

  csiDriver:
    name: "org.democratic-csi.iscsi.hdd"

  storageClasses:
  - name: truenas-iscsi-hdd-delete
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "ext4"
  - name: truenas-iscsi-hdd-retain
    defaultClass: true
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "ext4"

  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
    # secrets:
    #   node-stage-secret:
    #     node-db.node.session.auth.authmethod: CHAP
    #     node-db.node.session.auth.username: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME}
    #     node-db.node.session.auth.password: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD}
    #     node-db.node.session.auth.username_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME_IN}
    #     node-db.node.session.auth.password_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD_IN}

  driver:
    existingConfigSecret: truenas-iscsi-hdd-config
    config:
      driver: freenas-api-iscsi # required

driverConfigFileSealed: 
  value: AgBMs74vH2T2T+k0LqyS7b/EROQBFT2klDHHyc7cNUPALBG6oXsB7ujUJowt712sSVunV9T7plr+aYvTh302Ls2PDaycNPV2VcXXib7nLOr0UhAPtGUb0z8o/nmdHbpagWYtwKwB49gwlQ50XhDc+5D697cvjE8zoliSjw+ddaavWvJ5qyb5Yy3fYM0HodJ6voXYldYiVgNkn2ki0ElSal5kcIYjaZI5hPMqwOr9GADGckcz14/FuNWv6pxd13vCaJArqMVD534uac0CWpfsU3vbv6vryRNh4Bt7QYyRB8EaG3Lw8iADCNqDdcsizty91FYuJA65NUnJ3m2iiwongliFTuf8YrYW3OmvL2AzVsOOPFWGVhWHw2nAGH1MEc7//lY/AnbmuxDblhiQ4n8NI7oJrhNmkKpmwNRbSswRHgcBAtI1KGY+Tmbegmg2yn9PM7hPEJvz54e8/adDpYcCPcgyiYEYWfB8S2Ou0Sj+ELgCX+fUF+1TqYy38zNy7TfJyI2yR4NjSDAXMO7q7n+eo+40hWRZiikprLR2YSkFExTDi1KvIoGEyzX4oUCw+sM5CbHwm+SN/Tgjhifov+vjuzVEbU66eAh5eZWScMWDzpilwtzihu4b9A8BaMZVyxgScJA2uSrRVJ5X1eLzAdcKCm3IG5549DOG8pMQhEkfcK+0V9b/lqqG8HWC5pic/jGE9gaoMxfLlEM5kAUY2iOkAdUzow3tq4irB6iDaVb5ph/k7ay55cWQCcsaeModIDhqgQ++8hUY9oc4qlnG3FgorcglOPP8sA7WDPA544g1uVH3Drinwn+3SILnAgbKYJ9A4yF9DTtLWwRAMEm2+mdH6L5dS469mfALaFUdld94Ek3Gxwaaq7nJBqq+L3I523Q39cyteyLyzrY1bS50U9FauyjMvQxHCSL8AXQutoM5PJnNfDCqkJCYWxpHdIsP4BursF7ZJNDo4iS/MjcZqC7WBMIShlF7AKOr+tRJ+TR2VhZYCpqRc3tJtJdDyDeRWsHA8loiWDAAaDGYMv7zQaKhN7bANAws+3/2UGAWQt+WXoGEBEirTpN4Y971R65zXsESMXhuXvSHgK/eEgrzoC7H6Ky9RdlS5d7nI0A+bBVkwgXftaw1rvMubd8JYtplsNJJ6YylKa3syj6yIC8/5opmD5LT+Vy1qIhH99tZ/EX8T2IUjz7baaab61X+SVP6CWbk4BaVgAYG9oykHUQHxqbpqsmzZnjLdAknnXXaWI56Lqrlr3vT8oeGLiDve+um8Gj0X+pCbRl5S/eQsPoE9SVPOId+OlO+AxK4DxavnZkdPYkX5WMsD3tjm4SQHE/DXk5NN1ncbaMy6uuJopy5/8yH8nIxIdzq78t6UrPWK70Ri3QAaexzmIUnZLR0zayrNXcpJ50quhW9148pF9I7IeDnjAerp3/gtixjdau+745ZypGXFhgrXVro+2xJK+uZlkRQGDcF0+Mfb0x67WAMCywqAj2LK4ohVMg9OGIr7KtGPGdpTvXW17j7OTpmELTPCmWdR+c1J5mvEzVwtl9wSRpLXIxpj9BC8C9KgwWUwB9+rxlmn0qoifroLJBSiYWadcMzypGvgyUCK0kzu7bU436eMxi0FF9l6gM7tZCUZ0R07EROWeTf7Yy70wQcpbuC5s20WG5sxVtsno8gkaFFHP4kR65Z1ySJH6DLRGqcHHmsYsFFRtYjEhkbK7WlbZJCzYlJgShiUCqYWNpQrIuD1tI0vBQn58ef9ia24rHFZNcvOtFXuNahn16rIFhFAE6bSpPAhYnLnMBRFxdsuZyjrk3WdQxE8n6jLJIYVXcPXTA1cr+kIwUG7GfgwlsPJJQ1MRepQibFY7P8LNI0rUqVloGFuHJ2g/FuknXI1+QVeYmtE2Ou3TEtRfnhCRWXH5NdHQbSWvpBg6oRWHh3PlNigBUesFlX2TCnAvMwXXwvQo4+UDQRcO/GyKmL1ChveIx5nNAFB7I06pLvmzZzlaR1V2RN2Zf+uzL3fm7Xme040lKY+k2tY3wZTWi3LWXNNjgE9YazT7TRPWyoX/Z0Hf5zTXuEqGClCNpPJpOm2l9Gflxaq4sHNJHOhC/oPQrQrf7YPBZLaZxYeZCg416J9N0adkD7FItjmwYt/TSOXY5dh8ezYOBRNsspirkS0HTbl0hfJBK4s2G2Finl1DIy1UKHJBQCyEaNjyoFLB3jtbArMkpZ9ag9072aRLbw0mi8zNVNHFepaVt+r7xb9A/r8w3sJf8o0bhhRhPSznpVSb224y5gX8pKzWqbIqRr9RlTWHWQU+J2qd333ZAS0s+h27pJoCGxlMbqjtIoTwQfY9MM2AwyeBeNNuoVDfpJ7MaRsHL1jDvTDmxfiGdLXDTdK/UcBwDfwxuqzbHIebnYNiTivrc9yQyHjy+PrCftBTvhKwqgLevhZZg+IwgyIkemYRpWTtDgOKPZN24DAe+VEPy05Ue93i4+B01tmbMYh55AMxrKrsv7w2XcNM8udV8MI8VTzPBw8yqcfNDOzm1/v6CgZVpOo0UKPPQLXQrMNdGrdanTiqivipB+t9nZj8WUGaK+EqN96kqnE+eg8IM9oTivtN/5w5EzZdGy3HAwsgfxxXnIPwuz0NQ9dlbqVyLZ4zl/1/kz2UyFiRa0BcfW+PlqPDXtd+PTKlJZOtVqJR4zvi1nLvsKX9L3bjgtzmyfYKyciTnuO2Gd44TLRo0OsPzlZNUaASzzm5zbsdWPwvMdaTYX7mvQukEzyENKHMrvZ9PNDdWiW0oaMqzNLUYvknS/NxWcVzRFTxyR1rXTLV9RuscAm7hAb32sgtnvTeInqc9a9AKW16bKDo0I/ExD16yQ1cCBjhb7QbbLGV4WTqQGZjfrvyHQ8CTevSEKkp6R5lAHa2/KF5/GOSgGH/5M+ON+zZXvxFysZiHgQasXRh0CZEVGSaGHOqloQNjQ+2AgCwkWxB4ZUkOLQ5FIrRdlxQ6L5uRnmQM2rArRYA==