democratic-csi:

  node:
    hostPID: true
    driver:
      logLevel: debug
      # talos config
      extraEnv:
        - name: ISCSIADM_HOST_STRATEGY
          value: nsenter
        - name: ISCSIADM_HOST_PATH
          value: /usr/local/sbin/iscsiadm
      iscsiDirHostPath: /usr/local/etc/iscsi
      iscsiDirHostPathType: ""
      # talos config

  csiDriver:
    name: "org.democratic-csi.iscsi.hdd"

  storageClasses:
  - name: truenas-iscsi-hdd-delete
    defaultClass: 'true'
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "ext4"
  - name: truenas-iscsi-hdd-retain
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "ext4"

  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:
    # secrets:
    #   node-stage-secret:
    #     node-db.node.session.auth.authmethod: CHAP
    #     node-db.node.session.auth.username: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME}
    #     node-db.node.session.auth.password: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD}
    #     node-db.node.session.auth.username_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_USERNAME_IN}
    #     node-db.node.session.auth.password_in: ${TRUENAS_DEMOCRATIC_CSI_ISCSI_PASSWORD_IN}

  driver:
    existingConfigSecret: truenas-iscsi-hdd-config
    config:
      driver: freenas-api-iscsi # required

driverConfigFileSealed: 
  value: AgBQSS846PmZ61Jc+pwIp42Ft8ejYoIujyzLvQalAZ/tqeCoG3FK9w8BZfXW/CWYZfB0yfhOvmzPzr69T01HQXAxb0iVxfJ+E5zMuC6XoZ1BvFsghDdO5zyYcg7jsNUQbetmESwKrWxbTEbl1kUoF0ur4kHcZhM+Ua9E3cJm8posmx4MjnyCNUUISvAZ0pv/Y0lzlNV3CsRWvwzpxYv7pxX8mJl6h6vGK71blbvqNToZViKyibeqsE7Id156Equz9zZyaXiORJAC7ly75NB+F79nZGh+p2GzJnRQx/MJJJJGhUHaP1uMvQd8ACqULWQlzhHuhYBFTTkny7QnJXxP3B3mYOsMRAFIKgDKp3iVgJQHVcQeBXL+DrkzYunTxLjAhhEzRay/GG69p/1UP6nt4visiA0TpGRKmfFnh4sqMNiliLgrpdDDRgWi7BWGz+uRqLMJ0Pv/Yksk280IkgjMlIoCfy6MHmtcgb4+iUjCW/AU3kwJlyQKu6hmS+NT17+cUWxPVD1hLx7PjCqgNXI1xbMGCNJX4LcghPeLhp0mLbelEq9n7ZqL8/Q6Ku9q4bumfcgY7S4Op1R/CNvp9giZJgcWhCTGOt2WMITTg3FWvpfet7UqYebLdxpBtr/T4uVOZ1+q4ntzhcx/YGCX4vAtabStVFbCoXQmZHicycl9IYjhlJL1ABbUI7tOibBrqUPIlC3KCos7ujAu6qDeSYTSBB+7jiVez/A0GiHEztrx2wjafrTycMw2t4ixgRy3KHJwn3/7Db1ceWoHrRGEpr3N5n4kSwIu/C5lqHy1DuOiYy7yzrfdxUrB4FBPAlnluvjEGFpeiWEIZ1hrqkiFaEA9/KymFEF2ywVQe4rMq1FTz+mNSTwA5Yb0wnXe1u304R/ALnqblVwroQJqn7S4h8ig4yVR9rxe0FKPpv08dZOIGGNg8UgKZ8b1P/4hLE+sgW9CFUYBHq6BRrh/1+/YTlp6SdwKZPPf/frntz8mVhmZrQL8C4nerFQaSuzYoKAIPDw8Ul/8CNjGTHT/mpWeK2uLpv+xsEIoycwzw66m8DTg34pxr3BgB4usZ8d5qWuR8uelCi3DQ0uXmHuMzJ27fMrm17PMGNqUtq5Bf4qL4LehR5pucbEbFVYin+OMUGoJExCNuT4EULJoe2iVLjZ/FhEoCMaBjtOVqyt4jI2XoBvBFcKrbc/96I0dp1tP4g1FLlBq+JNt4UCcQM2A+moyesOSmnyFUxk6y9gRoWSH5pn/YDA40OHW6WpCcIIaVty+CgFdPwu6uumStmXR09Yrtysls9ZG9t5fUfQEZsVpVdXI9gD5pHevWyGbSvOHyFZsNRk1I1jTNU2aZHTc80+QF6JH5MH1wdsi7DFAMxmIVEAqTuuRC5111p+8E3biObFwLNEr9BYyu8uSmzy4T6vNBY2m2EL0oCMGnDcc+Edqok6KAFJllICqUGDPovd9Bt6YgxR1kka0v2ucYbao0EjRqZBXwqqfGOOLI4cLSPiR0luCuBIjwj4Nwbd5x5ELzsxHmoz1IqOhRzDc06CEheHJyQPpFwux3qwbNb82Xxx0y4Fw8nsfpKVYGY1j4Y8dVCmG08N1ayeQuTfVznlznkHlfr8D79ixL/Cw5Kbn/S13USP/hztcVuxSVuYlwf4VdsmFJpDorORF8GNAGH65fOOzmOjVLI0PEXZKDbuo1TO1sJJJfMBqmn6OVgAh0RaZxuIgTt09q2tUMXDo8R4+YWfExQvYTyH29NWEm6RP0qSQNW4ziqpxbHchtvUE/nrPA5OJyIQKF9KKdMve5ktijyed5aJvzW4bFvO36JzkRmOou8QhezofCzx/v44eZCsC1SF/fb0cA4gd3vLoPUPWy/jumfBmh2MPFTdtaUZseIo3epY+ODMH+LZrh8a9wWuWM8AUsGCP7YcaPbsfRqfH6dFhmri3fhMt6BKCFRChDGMlW+JhKV0PvG+Hq1OdAyAcXh1jNoRF5XGNRwuXHOlx5M+2XBbfUXDExTl66sFgFhw17bSilsije1BcE2rLs3IstTuas8GUQivmAxbcoBxVXWCxzT8fi+dbs92asIau5JchimjFLPPntaNpr42GrVeP5SBbvUMeXQrsr6yJUCzxykpmPfK6F33A/qisThlHHM0ptBZz5kKKY97X+mJYCblgRVGM5iHVnl87HlzWkDbT/nJI5g6w87+G35uvhZRWQfM8UjJeFngHr00TIc5dUY6cLWwEJTh2qwUQpMusSknLaFhM1sCRhHkO8Sak8wVUBrV/UepTZQOauprnzRVh68SotnrEN099U+hDlAopSagPhXC1Og4vsRm5lXbSyvGPT1FDBfWFPt3lc7OTPo3xlGKWLYSmLaBm/1Y64GmNfwZBwVpwGdtfBoyA2rZoamVz9SXzrsRBTRO3+HVjLTfPwjLJMXOoJK1G1KgrXhvbD71DHGHPLISdixcQBm8m7iPAsQaVkxItv2lu/AmTa7fVWaLw9qEMeFGVa64nBh/AmxIxv9+GS3L57cowf1NGvqVR3cp18rlwyxi+VIyDknlYTKnpI1w4ZBJcN4imKWYmnLPtDDttNMeNUSRDkZHaVOQx46fTk1JeMgfPHBW99fJFwuOgLa4LjOosWAgmgoMUVfLDsl34zBfRjee/ANy3D5rINfnIZOjs+Tb4OFY1eRm6e7fxOM0Ir+5dhUywb2ytI/o3vSd3fYsWOLPXkGX4CzmBup2TPdZ4zLJH8hnZvC1DBEahgBKeqBwTJfHXObs8DfghjZKJpkVk12RJKN2Bm1/Oj+CrKZDqHuYpPCJDujkBUc1UFuFQXdbsZGPTR8Qkj9KQTX1MjdLp1Wje4peaTfFEPV5Pyz+TRMHRgw6aTc1rTZCSdPikSInIXvqF4fUms4oBcTtL