democratic-csi:

  csiDriver:
    name: "org.democratic-csi.nfs.ssd"

  storageClasses:
  - name: truenas-nfs-ssd
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4

    mountOptions:
    - noatime
    - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-nfs-ssd-config
    config:
      driver: freenas-api-nfs # required

driverConfigFileSealed: 
  value: AgCyPc/xtCZPIGuWnjq2ElF0HSt+BD0eCG+pcokKzHKqWo1PH0cYk+BlXX3bM5jq1v7MJnzs++dh11M6I0kKeRtNbCaOHqYF7Rr4gZ4s2pDzfghE0qBwHuz7tVAjZQeE3ALdkPU6Ls+rzVRgX6tQ7j6lhiZuYOX+f5a6odTKzSyyK2XXVUYWXtFDjTuS7ljDURGeqku6fxHSwSrE7H/YaKjtKmpxNgg39R7UmRj9aBaFUqIgn5SPUcJSdqjuZxICt6KxXrUdJu/Ucjufr6QeR8yuSl45oFXKKxpoFsXO1JIEvqwGliMsxIMNRZYSYxoT6cWPrNb2/wU1KJ6Gts7zcbw9E5rMKG650vHNB00VYjp8BP6JBGGEIFiW1qBuPjWIMlHDgNKJG0NfH3rJCWDkoL6nw0NUenvPvx81tysFb8BB40VB9CHFP9hm7kSmN7lB5454l090wLir4e/oDPX2Mt17VOolqHGY8QqKqmMnsH//ad5g8nYOgddt1/QCE4q6Q9/FWkFY36RpX5/+uElNsJYpIHoqk02F4oBwPhxpR3C4nqBv9M1HMj5zmRltUvHHQaE7SAxdvANS+cb0u4DMkV/AXQneh0neLQgtt+8tKdOlkys18JHdYh5Pc+oWy4pP/F1EqoAxFGre+Zb3MD9eO+400seFxNldq/xflHur0JvddTeAkimgrpme3OYWGAEDmLLGBd1/2aAHOzfrCbTTidgE8WzCC9klxDPtonMbH6bbm1MkjE4YaXZc78x63AqgU5cWvullTbXAiMa+EDUukv0IbEihmrAQB1kAwwMVk+cGzj+hZ6VMu7BBENMDtBBi57GRKOVlLxdE2oe0FKYNncfVisW1dAcTEdrr7uoZ4T5HO4gA6Z/Hr3+XWyr9EBm+FFBC9iReQnmiRlwxggqkWuj93cp0djtwpGOAu7beeA0NAoSXinyETuzl/+9GiWDqs+3SNiCb3ktS01ffhub2OdpYoO8Gkhg+pg0wV5tAYq0V5nWPfHtCMxpr7cOIz369ksD7o1sYky69nsVHkdypZxvcKAo1iRd3Pw4Pi9kivNUf7JNJz2LgzwGxBH0ZB6hsfMfgKVsRL1EofeILHZ75MAKbWh5FweoDjAUVbgiTaxBpNVxe2U3SYiMe82WHiZSWx2S1Uoqu4L7+fWfrXupezPvoEU766eKpXx3NVIYRv/OHqD3TzM/T9GUN+ltKF2SnalfIcqGMl6AI6HapgoMvbAEC9F02Tp9BOy8djg5omzTh0752CFTSE963Y7+NDmkTXMGGLKy4nb/LKqM10t6JdRdbECWnMLk/ps7TE2q5kdzCkmA98wqvJKGKb39oy5EkA1MUqvgJyKMkv+CN635ftdyZtLDdg33KQ3+A0L3w8GQkXNgsRHNF42BMUhgwyG/Md7l06eM8XQBO6kNXbQjdV+qohKbMuuFKXashX2I33nj0VXWiF7RvSUuAaRXNyBwu54SaZoPrqQ/+AzHHn9LFf/VdWbzzc5DecoVPzOE2s0eLZa9Au4Prtt3Jb5BJy1c6/Ho5WwZ4v1RTxPvCGGmDjXcS3hbm5173mz7CqeelMLSeoVwn/wMQpM8ej53avPSwzuKL34W0U0GN+Xe9TOFlvHYywQ3V764es/bpB47IQqUkERVWLFsdxiBiCIw5X/jvYyqfumSbJGqV49tmn1bDF4AD4hw11FpO4d3G5/0FHmuwbOwNCkqoOILq7rWWO4VsctJrnqAr0Ahe23ppO6ZP/ShuK/Odcpc3B7f1D960e/Wq2rvD+OR38eVkLa5VQqSxVvXTHJJTxqbMonlgyKu5c7cA0vbPjYTwNss1PVzQop4mMHMCa2da3RX9lcT6qQ==