democratic-csi:

  csiDriver:
    name: "org.democratic-csi.nfs.ssd"

  storageClasses:
  - name: truenas-nfs-ssd
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: nfs

    mountOptions:
    - noatime
    - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-nfs-ssd-config
    config:
      driver: freenas-api-nfs # required

driverConfigFileSealed: 
  value: 'AgCaDjhBZx6GppDiMEISy/zyDpgukCIiiB0rEig+2DupEbMz+goIYefFcghqu5o10qeqsW/X1YmyBgmIS264jvGtm6jkD2pvhNltNGhrDneH8j1fTaC5BloCsyeQ7e2csEYGckvB6DKWorczuhDwJWgqxUUR6lcaISJ6ZHsTxA6to5p/VbA4QC0/HwLcYMq50NsUbvkp9Y18e9f+jmYFcpRM667MvHYFri9UJ9yR6ngLfktrDL8RPzAN1WtVLI3lrzL1rsBJyr52wLheG3+rkKre/6x0MmWP7BC3yk/g7efL/2H2RgQrKX5TpKyHXshOsGm9++5vbn/1cgKiL4becJbLST16K/xYr9VaiHA65W8+zJqEGkg3J+thhsI5AtczfbxeWv0oIjPyIoPV0L9kWHHVIXH8q3dvGV/9Y6PM3j61KJ1gHrtem9e2+zXhuhu8ULW50QJKs/6JOv4RoGW1Bkbtc95Z0/8Q2pFMjJqwQf0mClW9J3XQ7UzIqoKXjIrjHmvSHtJBnq8fTkpcjPO1CAGv87WhCJoDl+WuDc9ZMguzNkI9orYuv69tRqT0mXKOqUrNLd2w1MnyJfjhWbMosav0FNX8yRPSy2+we8GUWxbK0krdkQ56h+aL6w5frdw7Dl7qc+FI9F8UbPMdqMdifiHDZAIqTujqs1E3Z6rVOVDM1iY/1IM5rOGfGScM3NIYT+i0azDV1d5BMAmrWLY4aRjv0IauwLwPw+quJIftid8peDgGcTOx6o/zfb2zPmu9pha7XJPsnKc5qBpssoU+M2DEelirgWkVeD3HlGqQXDy+5uPs7mAapDa74+USPvR9taO6ealDp1h1vw7OIO9GpUwbjftDGyMyNBUzHKO1F2ktLAEgF4J6QxEhdwe0Z2I0JKf0AsU91gjhAqt+xmZtx61pwTkv8Fg5UuGXmR0ICBvej7Z4bd5srzBfSoDUk0y2xdsNLhgKpzZHe8I3/v1Wh+STd3/jGOQnwSaAnc1XNIflUTPEtx66SsVkTSQeUfsY8F6pvT6yIJbAGrtXA1BWG3GJxUAK5U6/iiVrY+CZ2fwwQTVyyh4mzZDJElpNcSJf0WZ+I+U0I9RKFjG5T9MnztoaB9+mHg+Fy2pOJlxW40WArM4evLGSNN/djz9Q08qKCVjM1T0jnsFDEt52H24mGwJZ5yfVL5cbFhgzIQOIV8D/ykeF4AypXvyNPZdEoOVZPFNeuKQGoPhsf5MWUcgQp3Dz9ZEykI0gvCTflBaeWUXSljOswKf6dgWCLmAE760KJaRKSibqxIjubMdPatDqWhoiNbAlfokAexnSLS8ZelRBnbf3sCpSkfEyoIs05pzic39L2TjDjwWyplmCu8DbRiB9XPOGlJ9kYJTHO4KEiMWue5oQta6cQHcCR2mP7HtUvtdHWOkpZ2LLSbDx/9jlQ6Mpwl7wDIyiNtFOXNJupTnQ6wplkm/k2g142NCxr0Hs6/f/oncVNfkP8PIo40f3EyLS9J4PpSin3ypdB7Ukhaf7IIp4QN8P7vPyjLtTcLb6MxKSuE1nIJONdQOHEKPoAhNjh62yQ/SWpMZuOcngxr2GKqxDvVsE7X384YS8L38s+WcBVU4uuZkfQoMlgMrWxDWq5QDlZNq0OnSIJqjdfWLXQVgp/viouM4IrmhmqpBryWaudw7E0Gm23FR7TxLwMFUdNExav3WDlhQNex/ont6zCf3LZVhkjdfOqYHqzkTAGkJHhZ0Sam1U+FX+dr3ChbtxBkDf3ihanIT8Wbd9vyc+TKqxkAwcGPIkjDgn/tn8d4A7Xque2aWGMXsXDbCaJWCnJV5LP613HjRADMD135vZqrfUOGuUBWFFwNj8Sg=='