democratic-csi:
  controller:
    driver:
      image: ghcr.io/democratic-csi/democratic-csi:next # temp override because of https://github.com/democratic-csi/democratic-csi/issues/333

  csiDriver:
    name: "org.democratic-csi.nfs.hdd"

  storageClasses:
  - name: truenas-nfs-hdd
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "nfs"

    mountOptions:
    - noatime
    - nfsvers=4

    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-nfs-ssd-config
    config:
      driver: freenas-api-nfs # required

driverConfigFileSealed: 
  value: AgCzNAPj5erPLtq3G1x8rWPsZr0pRDg586BK76li5LXTJa9JGAbHbQ+fLtR4XkRSVwcNGJIlLH1IRq5C0FA6G3n0MPgvWZTQN7LPIe0qOZ7AD2s9/vY+Meud4mTEE9CtNk4tmRpw5r4G32g9dfGpcr+aoIZLc64cbyoGUTHGRcDarehHS04GvoGzdO3362ci92oiPOn6uSQtiCnWEASJF0Jf2fE2pzrpI3HxZ8KjjyRKGW/1PKs+u243+k4DF2NxqaocZbdSAu9y+KeEKb0xQ0Dyk3q4dbMnwiGfHilfJB1Nr2oBcsJQduopnHqjUW83CWzUmwtnNVaS3SQD91PTFtj1HBpHqYigcjTpQdzBTUFjH086t/9b9iBQg/S3flIE2RTaxXzJ/u6o2WHk1vmQrpQ+uXQXaaqsfOS4aNTvHLsYO/hCOdcKSO8giGVQPqM2Vt9HcLPc8D8CtH3omChjO5ZwAzZpPoamYIxTEhqJWdagUNRW6svEUcZMMNwAtILX4tDJrCN1Q/CHUFS6d+iMJDARLHfx8ae41NUKL5mwqDIPUKUO1+Ukzt3LgQslRZAU2soS0JbOZ5LxktjR+bW2B9HTaqhX0AtC+UTAN0/V/CVyTYkpux/tBtx95+JvfxfCmXkIwQTu4QCOSD3a8u+b8bkKJyymIyFzGzQe4/O5UWzgdTRraupWKWFXN23ZoZSSUpFvYOvdm/4txCvBz+N1niuuDF6ThWZb741WWmObFGmzo233knS+OVJwcaLFDAmYQ1yJ17QdHjJ7Z4HEzrdNwoN1K2QhGN9BcutFxb/w2mQZVo2ellGQPjUZ3dI3sLKVcMWOaOit6303Z4z43rXM7SXbOfN519VubFpe1875jI08HmSuvjdxYNmS/ubbgETK+FaISUC+PKWNZQzq90Yhr86B9PhyGiFoSJAzDjyy+9i0aa9m/jEN70QncqFdDU/HjuHwc6vtjY9iULRT9m3C+5AhSP6PrEYvpHQR6UTEvPwcONHNuyqbGDQwBNSCVFjcYlaFmgkWGbchg6u7bLucohUnAX1moFzrCqTU/mXNN4UixRoDGFi49WpokwGBQUaZ1/jkw/acEFPOFsVN2LxKgkZFuDs+KoDVLP/tZuDlyL9OuvKjD99JiVaanRCeTCM6cgoMyMS963d0/s1fw/Aj7WyOgjwXb4ZupTABG/Z5XG1h5wzX5d1TE5ih/J2uXPxvkVAWao05RpYQtNkBdyaDawII5t9KJ/O8Pow8lmLbP6yDp66d9DdlJksDEQiziXC5zb7PEYpz+hGYzhZuO4HvQKMBSDKBdyeBpHt9LgCCFcsQ7XZGGemCfcx/peWL/DidscrJkF1QBoY/iYkbgV8BvCESve852dISZCmL/B3AIK1RuY5pMb+go3mSgY5gstP4iYRmhY+0jgx+dA/Gp8EKFRl1cjlih+KKJruWkZqZsJ3jlk2afkvHiDuH+KFo73dgoCnJsuZ4nbF0gS/cikqgrAVPRraATMTvoc4y6F1u9TXuuMuvo4kJuIzOtrdY+66NEXEQQu8c7y0FgCHEVvdJc2gXINrydzUjNXd2uxlAhW+CZAI/q8ELoA+0tkbbDytRyPilQYJziXThM3wTy5NMzzgipdlr4SD+yqPXHK2EcAwDeaHGP0sAEvtwsOFp2SmC+vPvCJyHkIIMSMnTRT9TSdTzhJLJ4QuEU1THLznxstrA2YQWFz3SLqeI8Gd0vEjGJYBq/rlr3Jpv0XjHCoIgsGPzTjHR0pKrnMq7uPXWmYnnVGhPZTtobjmy0HYgF0WkLyyC1LbkEudU2CZ60dqZr2ygMIc/lXJ4QiSJF0SdVM7IpZpazIstIiqCr23CAfiKUX17hzf8a1grU2R8rbT8U1E/eIA7