democratic-csi:

  csiDriver:
    name: "org.democratic-csi.nfs.ssd"

  storageClasses:
  - name: truenas-nfs-ssd
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      fsType: ext4

    mountOptions:
    - noatime
    - nfsvers=4
    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-nfs-ssd-config
    config:
      driver: freenas-api-nfs # required

driverConfigFileSealed: 
  value: AgCdYYu8cNH/eG47K9sr5iG42CFIlIlKQMvJ3d2rkNxVU6zR/XyMRpDsDdesCORHtKnicKoF00aBW30RxggSR1IEnowgdhIS8v3MneSmibO/fOSqWzqTB3BS4ZWX0Wa8IyOt9tKb6DFuz3g9WdGv3L/6hm5oMNKAtbV7JjHqaihy5FAuQ6qvXOT4Mxfk4hEZdYCRPdOn7zEq3QWqsMPLjEvaKtdYnP+xDGX+3sYqF+Y0JH1LYPGLyoalnRKAmj4YEBGBii62lslpYDx2O6d1rM8Rz9G8zALlsLjzaO/iVT886pRc68glxFFaU6m1w7CnEVdV2uwUwmNOhnBwLZyCpLiTpnlOZcfmS3cUldKNOsMJdEAWpcOrmnx/bfFMYtg6/wqMztcYN87cSuqF4GWmND6kK3LE2acRGGRNoIc4mJkbqO5Ma/8AdAqdI5aBpyVqTVaU9X0poLKZku5QnRI5GwUMgrGLa02VbTDQT0Fqk0//yzm+2bM6dTsqkJWPKBMkIRfxAKgjgdRV5n5Y0OjSNSUYfUBaisQkcUn+SOTW7hUvTLJQnIanLikIybtHDqF0vsFT7FucGAo/wrI5V7RRpW53FNJH59s+i4SxmyT424PK+y1YAuOonf6gQn1mBgoKUwDaUl6Egq+oQ+gBSljhx3HTDpJgOYpbOvKB/rHBz2Nk6NqGI7tORnKNqkSk+Mal4XsPeOF7EgrtZazp8kNypqnD5IwCzgSu+EMVmRjiYvuK4CWxf7vlKrKvO707Ipo8gGJjJhx4J+ae0M5HvTwpN6igjtBU+ZsXBEcwTfh0bWpaqrs45lA+2+sX+gkrR+XnoCCdLtY20nDhmNAnJN+5xvd1NuGCqY2lC9rFTZklkTZzUza+R1AX/IXnvwvzlUw+yxbdgB/XC5KqIv8WYpCJpyIm+CyNXYTR6nNTb0ScQHfRBblR0QvDuaaBh0P+nzURiWkvkdPSRRWrTqe0EZ4sbEEulkeR7kRueG/4gw3Hdv2bX5buaWx4Cek0ShuXCCRXZYMINpmMiqWql0X6gFMJmuzs8K/af+7yrVRTxXd36vfcdY1pVMAEsz0R7bFGwHaNNfokcVBKG3Ii9Ae0U1UXXIMUwGEoX48qBXUtSSa7CzKvdd8HB3ZKyQGJYjPH3Fu8UHIIVs4lWEGeJR8Fnb6D0SHnkCcSuYZSi68PCYyJbZSFzwVtyhM89IDJHVsdX7J04xZpZ+Ocnangm8RuERC5m4LQ9ggnGCsqSfFLK0DTp99YlFzaBpFwowuzzd186RN1kfMTf1XjQUDMCngX6pwccl0vWfrJkaMFUp6zbS5f0NEgnJkwh7gxOb/upWV+iKjA3MbfvBtYH7JUk88Gr3+U4MeJYvluPhntHLWnm1Kw6eQ9qxDwaWAjTRqABVVxuA1fMaPmDOl/BmVZnawKIZB1gwdF2zYepIqc+BeFM4eQPJcB1EsmurHgR99IyUS700tXAjALa28ULwxl48OIx5bpxLF+Evil7deZv8bkpUgmExyShgKlbxN3wMFCgihS0oM0hULkO5QwlMthVOhbbX/28ndMUMmHBnwCfeRULK1t/nBYdgg1K2NENDJDABBZhbtuj793IfMdE2tjjKg4KDOEpvArQIbD2tpRYj8TTjj0xRuTs656XmKJy0Ci1Z30ZDu5xrpb0oaJtUsyCiMNM1ABmf+V1Si2Ic41jeLiKihSWvc0DDotpJxRAnDQw2KPSBeexYpbR7Im6rNgE4H5bzSuN4zh0Wq/CQT9HDz97UKkRdoDmhd/vi4zzM12aAaNhXvWW8Xh3CUYdzAdDxMBTTSGrRUTia+MqToIVDj4ct0sknuyOKKqh30siwp85/7KRg==