democratic-csi:
  controller:
    driver:
      image: ghcr.io/democratic-csi/democratic-csi:next # temp override because of https://github.com/democratic-csi/democratic-csi/issues/333

  csiDriver:
    name: "org.democratic-csi.nfs.ssd"

  storageClasses:
  - name: truenas-nfs-ssd
    defaultClass: false
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    allowVolumeExpansion: true
    parameters:
      "csi.storage.k8s.io/fstype": "nfs"

    mountOptions:
    - noatime
    - nfsvers=4

    secrets:
      provisioner-secret:
      controller-publish-secret:
      node-stage-secret:
      node-publish-secret:
      controller-expand-secret:

  driver:
    existingConfigSecret: truenas-nfs-ssd-config
    config:
      driver: freenas-api-nfs # required

driverConfigFileSealed: 
  value: AgCumryEQHvXX+LN2GGm311r/hbTV4aKrICmPe4Mw7HV8wSUtf3oLeKTkFJr+smh585/7PSOllYrJJX50lONh7Km0BsJkP+HOZaBApwEkTLgOkrG7uO+IlfCfaghKESDYc5mwSgvg0hnTVrCLxr8iUJCHNIIFaXzFiYS3XY8pFqJ5HYGxpMvmEYF2jEkuS5CB4DmF5SKi6SEgTa9WTEr4W7H4tR7+JMFGoOIu4UY8j/jeYDR9m7nypp0n+nv9ayT6GNK3zDAKLuT4X2SSvrAi8TKrsRJ9iECwTqgrHYaVRhK/keRD7QzKiqeZ/CRVKFlzT5MeWU2M8b73EAZQgZklE+5ns8B1vz8WXpEhJNCI3vwjGTNpmJzAYZ1PKnUuuWqHKwJK1bVimMpNBz4MMsYe2osfV9znQ/VYLQDePyQGbHNSy0XcCbnRYeeRZoAA7Za/5me0ANCh8SMCOSMpKeCb5RSrs/jr+W16PMiy3e6Mi0pzFh0eBMQ/1/Ms9AszPAhbplIiJXtksBMJHvDCTtrVa0laWTsEiomJSGj0hBzn+zcE7QCp7WWs6/EO5W/j2gcYfZgvKpG/7XvSbrhErK5poYzpMcsor0bMUVylRrlsfI3vyyxujhzhFuxUlCHLVT7P7uPo+NgZJrUAEKL3NS21YVH28HoLDSEo36ZWkqSHENKYvUUG0o3aaop2C0l1fbLVJpLTtZapJqBsrWcfBJEI0Hh9qAHM0VH7SPQiJq9UbB3VWyiIADIx44HaUdo/RmWGxw42efDmOPc01aUauQSbCD1V4ZUlfhEc7DHqW+4nqy2BAidlKjeXGiACVklyzLIYy7078T9dRpS5DE0cfa1w5lkFldfAXw0/2TVn4JfCcvZAO3H0XufVs06FUROFKcZTfDYj+r+5csu4btkXlvhludOU5odvTMAJE5+8sE1kaC/m8YNvYWEDU7Zscak9okJrifq+WuLAb3Kp3Z5bmxYEin8J7Y7IFp6NN69Klz8JMCeceZodInH9MCNBGL0zkt72+AGMC2divExIgjymAmacmCFd001UiPEooDNrjB/mpLTzummq2MJbcKVO1/9PlnwjBQymtU4j3Z7TUoybP8kHAjoJq2GKGXsmUEr7gAPmd/nu2OF8fXIJDisWZjem5eu5rLe2BIwq2PEBk1EogqAJ0PorTei4tK3TurXspun3xBsWP/lgrf9oHz3tni2NUOfCQLNWXBIY928+K1h8lv5YwVpF5CpAGSoHALbv+6klOW6/DNSOUKPyXdWhs8WQ0TOJORTQfFBiYri9Pkgr3UB0aHGgyI1OF0wEuNocNPwCiZtcGpwyjjXabwxHCSK6kZcTUed7EA4z8QNbQkfIu1lwM0Xh/1LHJdWbEUjkxMm7Jyzo7vliHyzucLHQ8OLGx+LNAWLwKWtVjPPm+xLKu0UYWyVqUm/PEoAOvBRLSJYZUAcw9pr0RMELXCKvwiNskpj2SK6McrfYq2DOHYLXn6kFLp3zaIRGQv94B/n69KBpclDilqHEsVCdsvkXZ7Vvb2bcCipZ1vxDsnregj3jEQXIDgukQU3Ms1lQLzX3lYejOxRcEtU9zUPBpVruNdvbyz3VsuXoggqUgBu/xXhKIy3Xw4vO9GC/ezW6chdIjuCaBmDe/Yu96Fcmy83a47Clm6YM7Beuv/PXl1U6ghFrais91uRdwvhYwjn+4erRFc6vbrjw8v6WzIpUxviu/WEYWipQ8h40U4/NUZCFjrkCWRnrRdd6w75Zo7kA1ziKH5KVAAwm+ovnQkeMJxO0lKAGW/IhwrJZw1fbRQPqs5rKS7/i+jSMcHAzvRFC8jO/EzU/kKgCtiv+fW8L5YDAEGPJQqbnAQn2kEMOZJKG2UAQBVzL523nV9p