image:
  registry: docker.io
  repository: infrolabs/infro-core
  tag: latest # cry

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop: [ "ALL" ]
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false

config:
  secretName: infro-secrets
  sealedValues:
    owner: AgCFS6BLV2KVSXkPS09vumDFA8BP4hIYQqmSXtfxBvDIWXA+dHvHTWiL3dHJ/8QF8EPEd80VvNcJ/6m50atVy+C+U2PI+tn5uspG7fmSUKfhND39TCKAjSxJYrb1NGLhdrp/UfdhwO8AzSBxxdc7qPZ5MJce24jeX4eTt+P7TBm5P6VigYhgjamO3bHe0ekqBvwmRLMhWJdtYWLZkUJ4Dy51jRAZhvfPkELFhIDA5qZz82jUxSNzlDkfMjwEA1oqVZpxEFficzAb5VVoxHDLmZdigVwD9jkEIFtkL2mlN5xD2s22Ofwsoz+lvKb32XE3RiOabgrwinOPcufc1OMAhGorFG48+G2CfvA9hw1i49sxFTJUwNHnBnzUMKyq++phRrSoQE13DRnZgSlxnXRmji7PwkOyCu3bRyQIT2FDzTK8raIEySj6+nZDF/F3hVPEtVgbKJxBHQlhqnMBe8Sfd+0sH4zayfegwehQ183VwRqwwtaorZBOc1PYVj7jNRHMG0kgFGxUrDjfoAFKjM5e3A6EgZza05MQnTba/MiXcRfS2FZeRT8iWbcjB2NL6b2fx6qgKMJ2oLe2SG8jVKtCTcyzlMH44LRfkQOcP/E7K18Gpeozvao44KFQkxvfL2dGCeufGZZq6whLXUe6UYu+pwe87H0Awlk32LV4MvnXT67vkme3MAeIVQQyDQ8LYsT7a6ayMgDX3GU1ZUrOcphcqHuJCA==
    config: AgCGN6Djd77ubc6kxEvemcn3ge9nu22gG3hpbYax78wgFlpEAWmmp7mnaL+wGqcrXkU58ZBvsUbf3WwVbAffo6IS6n1Yp7FGmiqO8dHmAS6G8V/gazHr3kmS9SyOU8LFWJ1X9klV9wHZQNVMoM1sfdPNjRaCfHTkAARgWMD97PRVVpHng3O0FH4Rh1m1MbJiJWnAQtmjVxFSaguBw8xqQOQdXV0SceJylmI0uPxgfv7Sfv0JJ6qc/N0oTkdHSjo1KBs4fCUMwFguGaU0oUEEvYOLY3MhZhwANdsSVaauIxhiWIX73SRpb/D8nqyOzTV+57QMcZyMcCx4MltTd7vNyxba6TpxlUroZ0jNE65Qr4TTvoe9yYk4bF5p6T/hbe/Dy+lS/df3x6iglWm2HVvWGD9lOXU6OltoE8UG29ad92b1xPkifvkPiH9VOhFVRFpVayMByFu0WpC56tDV6Kybmgrp73KsSL3Bs+o+J01H7DOWX38m3pKz3oreUhMtlbVjinHaZkUON9SXQuDhjyanZ85hoF9yPPJBxDtfwOtdxwAPvmTZHFVqyNCBYEumq3/kURDVmYwtzwehsMVDQ3x39uawqQgDNEUzRwRSjBD3F/wTv7G6Pga42cd4MMPDX+sF6gHJ1bpDmYajjsqfo+QNge3JAPG/1bMPJWOuy7Rk4lr2iByva+L5ik/9wRzR3aaI3Hha8aS9M53ABAhkV8Nv10KpAIM2FBd+azr0jUJhxuiJ4U/J968z3s7il/4LTcq66qeROq+Hr1hRZSnNVClixX4p5KqpGpal+uc2Mj7gKZhTudrprKtymT1JYl+ulvYJe39BU6USZhtIWt8f6gw1bbWxxgYLEV2XPoatX7d70isChWFLiqYnAj3ijIIzJSLCSae6Vz2D57ZPKEwK7tcV/Za0RTqaKO2FSiAI80NSyZwsUdPnSkr75K51kWFYGSwrnbBaBSkq2tkWmCl3ZJR9OXYq3a6r+TgZp61yMMFfpvlEn9X9GEEXijr/MnQ3coSiGfEEfBUiTDyEvtwUhQGhsBBB77y3bk7QRm95fGnEW0CzAYByeX2W2mj3be8wAouTraIfxwpe05WX/1h23GPU+8vkF5ycNgsILgn7Bs8HTxaQ86SexZxBJLad9TcWU+UxPP2YY5PCUONbNiTpU4cRE8Tl/s8bJuDhJFflQblzTZLaOiiGZUtZC00hH93SfH9mc445qpQp88/bN7lR5GLdfe9U6RoeQ3hT
