metrics-server:

  revisionHistoryLimit: 0
  replicas: 3
  args:
  - --kubelet-insecure-tls

  service:
    labels:
    #  Add these labels to have metrics-server show up in `kubectl cluster-info`
     kubernetes.io/cluster-service: "true"
     kubernetes.io/name: "Metrics-server"

  metrics:
    enabled: false

  tolerations:
  - operator: Exists
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
