uptime-kuma:
  podSecurityContext:
    fsGroup: 1000

  securityContext: 
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  ingress:
    enabled: true
    # annotations:
    #   nginx.ingress.kubernetes.io/auth-url: |-
    #     http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    #   nginx.ingress.kubernetes.io/auth-signin: |-
    #     https://ping.mobrockers.com/outpost.goauthentik.io/start?rd=$escaped_request_uri
    #   nginx.ingress.kubernetes.io/auth-response-headers: |-
    #     Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    #   nginx.ingress.kubernetes.io/auth-snippet: |
    #     proxy_set_header X-Forwarded-Host $http_host;
    hosts:
      - host: ping.mobrockers.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
         - ping.mobrockers.com

  persistence:
    enabled: true
    sizeLimit: 1Gi
