apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mealie
spec:
  serviceName: mealie
  selector:
    matchLabels:
      app.kubernetes.io/instance: mealie
      app.kubernetes.io/name: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mealie
        app.kubernetes.io/name: mealie
    spec:
      containers:
      - name: mealie
        image: '{{ .Values mealie.image.repository }}:{{ .Values mealie.image.tag }}'
        ports:
        - name: http
          containerPort: 9000
        env:
          - name: TZ
            value: Europe/Amsterdam
          - name: PUID
            value: '1000'
          - name: PGID
            value: '5000'
          - name: MAX_WORKERS
            value: '1'
          - name: WEB_CONCURRENCY
            value: '1'
          - name: BASE_URL
            value: https://mealie.mobrockers.com
          # Database
          - name: DB_ENGINE
            value: postgres
          - name: POSTGRES_SERVER
            value: env://MEALIE_DATA_RW_SERVICE_HOST
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: mealie-data-app
                key: dbname
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: mealie-data-app
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mealie-data-app
                key: password
        volumeMounts:
        - name: data
          mountPath: /app/data/
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
