apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/name: sonarr 
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 5000
      containers:
        - name: sonarr
          image: '{{ .Values.sonarr.image.repository }}:{{ .Values.sonarr.image.tag }}'
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: '1000'
            - name: PGID
              value: '5000'
          ports:
            - containerPort: 8989
              name: http
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sonarr-data
        - name: media
          persistentVolumeClaim:
            claimName: sonarr-media
