apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: sonarr
      app.kubernetes.io/name: sonarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sonarr
        app.kubernetes.io/name: sonarr 
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 5000
      containers:
        - name: sonarr
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: '1000'
            - name: PGID
              value: '5000'
          ports:
            - containerPort: 8989
              name: http
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /media
        - name: exportarr
          image: '{{ .Values.monitoring.image.repository }}:{{ .Values.monitoring.image.tag }}'
          args:
            - sonarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://localhost:8989"
            - name: CONFIG
              value: /config/config.xml
          ports:
            - name: monitoring
              containerPort: 9707
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
        - name: additional-exportarr
          image: '{{ .Values.monitoring.image.repository }}:{{ .Values.monitoring.image.tag }}'
          args:
            - sonarr
          env:
            - name: PORT
              value: "9708"
            - name: URL
              value: "http://localhost:8989"
            - name: CONFIG
              value: /config/config.xml
            - name: ENABLE_ADDITIONAL_METRICS
              value: "true"
          ports:
            - name: additional-monitoring
              containerPort: 9708
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sonarr-data
        - name: media
          persistentVolumeClaim:
            claimName: sonarr-media
