apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
spec:
  rules:
    - host: sonarr.mobrockers.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: sonarr
                port:
                  name: http
            pathType: Prefix
  tls:
    - hosts:
        - sonarr.mobrockers.com
