apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
