apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
spec:
  ports:
    - name: http
      port: 7878
      targetPort: http
    - name: metrics
      port: 9707
      targetPort: metrics
    - name: more-metrics
      port: 9708
      targetPort: more-metrics
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
