apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  ports:
    - name: http
      port: 7878
      targetPort: http
    - name: monitoring
      port: 9707
      targetPort: monitoring
  selector:
    app.kubernetes.io/instance: sonarr
    app.kubernetes.io/name: sonarr
