apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/instance: sonarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonarr
      app.kubernetes.io/instance: sonarr
  endpoints:
    - port: monitoring
      interval: 15m
      scrapeTimeout: 90s
      path: /metrics
    - port: additional-monitoring
      interval: 12h
      scrapeTimeout: 1h
      path: /metrics
