apiVersion: v2
name: democratic-csi
description: A Helm chart for Kubernetes
type: application
version: 1.0.0

dependencies:
  - name: democratic-csi
    version: 0.14.2
    repository: https://democratic-csi.github.io/charts/
