democratic-csi:
  controller:
    driver:
      image: ghcr.io/democratic-csi/democratic-csi:v1.9.2 # chart default is latest
    tolerations:
    - key: priority
      operator: Exists
      value: Essential
      effect: NoExecute
  node:
    driver:
      image: ghcr.io/democratic-csi/democratic-csi:v1.9.2 # chart default is latest
    tolerations:
    - key: priority
      operator: Exists
      value: Essential
      effect: NoExecute

# driverConfigFileSealed: 
#   value: 
