apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-api-key
  namespace: buildarr
spec:
  encryptedData:
    'api-key.yaml': AgAcOhZZ74wAOxqJ5OJXwUFm2SHy/8WMHqjpb6DwA4HF2m8+3nE3+E6csP5Rm/KB0BZB6wRb1BKzhSznj8rMyPq1rV3qctL/ZoY8obs/Yj6bGgnPKJNQIdd3ssvekcirHuJIdzz24elnYHz2Q5t28YMeNasSUhfk3+7mnquLgsS2iuy1+bd266pV7mFgv1Dhl7eJaPUpVz4cndH7s7EbdPeY769gTjJ6UynCKYR124tVOntlLWtmwAvXgoVVddLb/2jYZ1MxAQ9ZXvC8aa6Ucq0/y5IcrYCg2bCDznqz5uXAevKmoPcNtzOukMUwJ79xJsgtZJJS8av70QR+lcFfkLIUkQpXk5hQc6/rowHM1DLlk92vesz48/2SEkUbLGS1CnTR9ezmErAdAAllPZKENwHK8lhEyjlO9e0G5pBVPn3DvCL3moeTrK0qhT3PcwBFlKVp9mAo0X52k8b08Ko1wV9fkvd/aYYeCmF2IUmCVfrYsX8vjIai0yyHzEPfOLBCvAVZ4Njvq1LB4X4n6WBSGh0PWYCV0yekNF1QFt4/Gvfx/OM3sfxjR3LjAq5TcFasMRFEE3M2L+sefAglFoQwBOKHTtvqVQY75EV2exSwR6Dl6q6OUdq0Ud1effqcQE+YNUArzLKmmjysLWfU0e52bx3YDDZ4FlkaFFI7BmColCZwo38DMU4/RUjOH2+7sqQ/qThwj9BtO3BkMlsdlRynwef/wgDOnJRgxwC9GwFbEmqXhs/kF3werW23Kvt68ugDZscG+B3w4KfJ5blkclgQpH/lHMAcMBGEEvtmZLufzRjPXg==
