apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: prowlarr
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prowlarr
        app.kubernetes.io/name: prowlarr 
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 5000
      containers:
        - name: prowlarr
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: '1000'
            - name: PGID
              value: '5000'
          ports:
            - containerPort: 9696
              name: http
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /config
        - name: exportarr
          image: '{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}'
          args:
            - prowlarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://localhost:9696"
            - name: CONFIG
              value: /config/config.xml
          ports:
            - name: metrics
              containerPort: 9707
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
        - name: additional-exportarr
          image: '{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}'
          args:
            - prowlarr
          env:
            - name: PORT
              value: "9708"
            - name: URL
              value: "http://localhost:9696"
            - name: CONFIG
              value: /config/config.xml
            - name: ENABLE_ADDITIONAL_METRICS
              value: "true"
          ports:
            - name: more-metrics
              containerPort: 9708
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prowlarr-data
