apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  revisionHistoryLimit: 0
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/instance: bazarr
      app.kubernetes.io/name: bazarr
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: bazarr
        app.kubernetes.io/name: bazarr 
    spec:
      automountServiceAccountToken: false
      securityContext:
      containers:
        - name: bazarr
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          env:
            - name: TZ
              value: Europe/Amsterdam
            - name: PUID
              value: '1000'
            - name: PGID
              value: '5000'
          ports:
            - containerPort: 6767
              name: http
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /media
        - name: exportarr
          image: '{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}'
          args:
            - bazarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://localhost:6767"
            - name: CONFIG
              value: /config/config/config.yaml
          ports:
            - name: metrics
              containerPort: 9707
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
            failureThreshold: 5
            periodSeconds: 10
        - name: additional-exportarr
          image: '{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}'
          args:
            - bazarr
          env:
            - name: PORT
              value: "9708"
            - name: URL
              value: "http://localhost:6767"
            - name: CONFIG
              value: /config/config/config.yaml
            - name: ENABLE_ADDITIONAL_METRICS
              value: "true"
          ports:
            - name: more-metrics
              containerPort: 9708
          volumeMounts:
            - name: data
              mountPath: /config
              readonly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bazarr-data
        - name: media
          persistentVolumeClaim:
            claimName: bazarr-media
