apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/instance: bazarr
    app.kubernetes.io/name: bazarr
