apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bazarr
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: bazarr
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: bazarr
  endpoints:
    - port: metrics
      interval: 15m
      scrapeTimeout: 90s
      path: /metrics
    - port: more-metrics
      interval: 12h
      scrapeTimeout: 1h
      path: /metrics
