apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
spec:
  rules:
    - host: z2mqtt.mobrockers.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: zigbee2mqtt
                port:
                  name: http
            pathType: Prefix
  tls:
    - hosts:
        - z2mqtt.mobrockers.com
