apiVersion: v2
name: argocd
description: A Helm chart for Kubernetes
type: application
version: 1.0.0

dependencies:
  - name: argo-cd
    version: 5.48.0
    repository: https://argoproj.github.io/argo-helm
