argo-cd:
  configs:
    cm:
      exec.enabled: true

    secret:
      createSecret: true

    params:
      server.insecure: true

  controller:
    replicas: 1

  dex:
    enabled: true

  redis:
    enabled: true

  server:
    replicas: 1

    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      hosts:
        - argocd.mobrockers.com
      tls: {}

  repoServer:
    replicas: 1

  applicationSet:
    enabled: false

  notifications:
    enabled: false
