apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overseerr
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/arr/overseerr
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    name: in-cluster
    namespace: overseerr
