apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
spec:
  project: default
  source:
    repoURL: https://github.com/broersma-forslund/homelab.git
    path: apps/arr/radarr
    targetRevision: HEAD
  syncPolicy: {}
  destination:
    name: in-cluster
    namespace: radarr
